'use client';
import { useEffect, useMemo, useState } from 'react';
import { BookOpen, CalendarDays, Check, ChevronLeft, CircleHelp, Heart, Home, Leaf, ListTodo, LogOut, Menu, Plus, Settings, Sparkles, Trash2, TrendingUp, X } from 'lucide-react';
import { createUserWithEmailAndPassword, onAuthStateChanged, signInWithEmailAndPassword, signOut } from 'firebase/auth';
import { auth, firebaseEnabled } from '@/lib/firebase';
import { addTask, loadData, removeTask, saveCheckin, saveSettings, toggleTask } from '@/lib/store';

const questions=[
  {id:'mood',title:'How is your workload feeling today?',max:4,low:'Calm',high:'Very overwhelming'},
  {id:'sleep',title:'How rested do you feel?',max:5,low:'Low energy',high:'Well rested'},
  {id:'focus',title:'How easy is it to focus right now?',max:5,low:'Hard to focus',high:'Easy to focus'},
  {id:'initiation',title:'How easy is it to start tasks today?',max:5,low:'Hard to start',high:'Easy to start'},
  {id:'confidence',title:'How confident do you feel about this week?',max:5,low:'Not confident',high:'Confident'},
];
const activities=[['Reframe overwhelm','Pick one task. Name only its first physical action.'],['Two-minute task starter','Work for two minutes, with permission to stop.'],['Sort your brain dump','List everything, then circle only what is due in 48 hours.']];
const nav=[['today',Home,'Today'],['tasks',ListTodo,'Tasks'],['learn',BookOpen,'Learn'],['progress',TrendingUp,'Progress'],['support',Heart,'Support']];

export default function NuvoraApp(){
 const [user,setUser]=useState(firebaseEnabled?undefined:{uid:'demo',email:'demo@nuvora.local'}); const [screen,setScreen]=useState('today'); const [data,setData]=useState(null); const [busy,setBusy]=useState(false); const [menu,setMenu]=useState(false); const [settings,setSettings]=useState({calmMode:false,reducedMotion:false,textScale:1});
 useEffect(()=>firebaseEnabled?onAuthStateChanged(auth,setUser):undefined,[]);
 useEffect(()=>{if(user) loadData(user.uid).then(d=>{setData(d);setSettings(s=>({...s,...d.settings}))})},[user]);
 if(user===undefined) return <Splash/>; if(!user) return <Auth/>; if(!data) return <Splash/>;
 const go=s=>{setScreen(s);setMenu(false)};
 return <main className={`${settings.calmMode?'calm':''} ${settings.reducedMotion?'reduced':''}`} style={{'--scale':settings.textScale}}>
  <section className="phone">
   <header><button className="icon" onClick={()=>setMenu(true)} aria-label="Open menu"><Menu/></button><Logo/><button className="calm-toggle" onClick={()=>{const n={...settings,calmMode:!settings.calmMode};setSettings(n);saveSettings(user.uid,n)}}><Leaf/> {settings.calmMode?'Calm on':'Calm'}</button></header>
   {menu&&<div className="drawer"><button className="icon close" onClick={()=>setMenu(false)}><X/></button><Logo/><button onClick={()=>go('settings')}><Settings/> Accessibility settings</button><button onClick={()=>firebaseEnabled?signOut(auth):location.reload()}><LogOut/> Sign out</button><p>Nuvora provides academic support, not medical advice or diagnosis.</p></div>}
   <div className="content">{screen==='today'&&<Today data={data} go={go} uid={user.uid} setData={setData}/>} {screen==='tasks'&&<Tasks data={data} uid={user.uid} setData={setData}/>} {screen==='checkin'&&<Checkin uid={user.uid} data={data} setData={setData} go={go}/>} {screen==='learn'&&<Learn/>} {screen==='progress'&&<Progress data={data}/>} {screen==='support'&&<Support data={data}/>} {screen==='settings'&&<SettingsPage value={settings} onChange={n=>{setSettings(n);saveSettings(user.uid,n)}}/>} {screen==='overwhelmed'&&<Overwhelmed data={data} uid={user.uid} setData={setData} go={go}/>}</div>
   {!['checkin','overwhelmed','settings'].includes(screen)&&<nav>{nav.map(([id,I,label])=><button key={id} className={screen===id?'active':''} onClick={()=>go(id)}><I/><span>{label}</span></button>)}</nav>}
  </section>
 </main>;
}

function Logo(){return <div className="logo"><span>●●●</span> Nuvora</div>}
function Splash(){return <main><section className="phone splash"><Logo/><p>A calmer way to move forward.</p></section></main>}
function Auth(){const [mode,setMode]=useState('login'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''); async function submit(e){e.preventDefault();try{setError(''); mode==='login'?await signInWithEmailAndPassword(auth,email,password):await createUserWithEmailAndPassword(auth,email,password)}catch{setError('Please check your email and password.')}} return <main><section className="phone auth"><Logo/><h1>Welcome to your calm study space</h1><p>No shame. No pressure. One step at a time.</p><div className="tabs"><button onClick={()=>setMode('login')} className={mode==='login'?'active':''}>Log in</button><button onClick={()=>setMode('signup')} className={mode==='signup'?'active':''}>Sign up</button></div><form onSubmit={submit}><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Password<input type="password" minLength="6" value={password} onChange={e=>setPassword(e.target.value)} required/></label>{error&&<p className="error">{error}</p>}<button className="primary">{mode==='login'?'Log in':'Create account'}</button></form></section></main>}

function Today({data,go,uid,setData}){const risk=data.checkins[0]?.risk;const open=data.tasks.filter(t=>!t.done);const top=open[0];return <><div className="welcome"><div><small>GOOD MORNING</small><h1>How are things feeling?</h1></div><div className="avatar">J</div></div>{!risk?<button className="checkin-card" onClick={()=>go('checkin')}><div><b>Take your daily check-in</b><span>Five gentle questions · about 1 minute</span></div><Sparkles/></button>:<RiskCard risk={risk}/>}<button className="overwhelmed" onClick={()=>go('overwhelmed')}><Heart/> I’m feeling overwhelmed</button><div className="section-title"><h2>One small next step</h2><button onClick={()=>go('tasks')}>View plan</button></div>{top?<article className="task focus"><div className="module">{top.module}</div><h3>{top.title}</h3><p>{risk?.band==='Higher'?`Let's only open ${top.title.toLowerCase()}. You can stop after that.`:top.step}</p><button className="primary" onClick={async()=>{await toggleTask(uid,top.id,true);setData(d=>({...d,tasks:d.tasks.map(t=>t.id===top.id?{...t,done:true}:t)}))}}><Check/> Mark this step done</button></article>:<Empty title="Your plan is clear" text="That is enough for today."/>}<h2>Today’s plan</h2>{data.tasks.filter(t=>t.bucket==='today').slice(0,3).map(t=><MiniTask key={t.id} task={t}/>)}</>}
function RiskCard({risk}){return <article className={`risk ${risk.band.toLowerCase()}`}><div className="score">{risk.score}</div><div><small>WORKLOAD PRESSURE · {risk.band.toUpperCase()}</small><h3>{risk.message}</h3><details><summary>Why this result?</summary><p>This transparent score combines workload feeling (30%), task initiation (25%), focus (20%), rest (15%) and confidence (10%). It is supportive, not diagnostic.</p></details></div></article>}

function Tasks({data,uid,setData}){const [tab,setTab]=useState('today'),[adding,setAdding]=useState(false);const filtered=data.tasks.filter(t=>t.bucket===tab);async function create(e){e.preventDefault();const f=new FormData(e.currentTarget);const title=f.get('title');const task={title,module:f.get('module'),due:f.get('due'),bucket:tab,done:false,step:`Open ${title} and write down one small first action.`};const saved=await addTask(uid,task);setData(d=>({...d,tasks:[saved,...d.tasks]}));setAdding(false)}return <><div className="page-title"><h1>My plan</h1><button className="icon filled" onClick={()=>setAdding(true)}><Plus/></button></div><div className="tabs">{['today','week','later'].map(t=><button className={tab===t?'active':''} onClick={()=>setTab(t)} key={t}>{t}</button>)}</div>{adding&&<form className="panel" onSubmit={create}><h2>Add a manageable task</h2><label>Task name<input name="title" required autoFocus/></label><label>Module<select name="module"><option>Dissertation</option><option>Database Systems</option><option>Web Development</option><option>Other</option></select></label><label>Due date<input name="due" type="date"/></label><p className="hint">Nuvora will create a small first step automatically.</p><div className="row"><button type="button" onClick={()=>setAdding(false)}>Cancel</button><button className="primary">Add task</button></div></form>}{filtered.map(t=><article className={`task row-task ${t.done?'done':''}`} key={t.id}><button className="check" onClick={async()=>{await toggleTask(uid,t.id,!t.done);setData(d=>({...d,tasks:d.tasks.map(x=>x.id===t.id?{...x,done:!x.done}:x)}))}}>{t.done&&<Check/>}</button><div><small>{t.module} {t.due&&`· ${t.due}`}</small><h3>{t.title}</h3><p>{t.step}</p></div><button className="icon trash" onClick={async()=>{await removeTask(uid,t.id);setData(d=>({...d,tasks:d.tasks.filter(x=>x.id!==t.id)}))}}><Trash2/></button></article>)}{!filtered.length&&<Empty title="Nothing here yet" text="Add one task when you are ready."/>}</>}

function Checkin({uid,data,setData,go}){const [step,setStep]=useState(0),[answers,setAnswers]=useState({}),[risk,setRisk]=useState(null),[error,setError]=useState('');const q=questions[step];async function next(){if(!answers[q.id])return setError('Choose the option that feels closest.');setError('');if(step<questions.length-1)return setStep(step+1);const res=await fetch('/api/risk',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(answers)});const r=await res.json();setRisk(r);await saveCheckin(uid,{answers,risk:r});setData(d=>({...d,checkins:[{answers,risk:r,createdAt:new Date().toISOString()},...d.checkins]}))}if(risk)return <><button className="back" onClick={()=>go('today')}><ChevronLeft/> Today</button><div className="result"><div className={`big-score ${risk.band.toLowerCase()}`}>{risk.score}</div><small>{risk.band.toUpperCase()} WORKLOAD PRESSURE</small><h1>{risk.message}</h1><p>This result is not a diagnosis. It only helps Nuvora adjust today’s support.</p><button className="primary" onClick={()=>go(risk.band==='Higher'?'overwhelmed':'today')}>Choose my next step</button></div></>;return <><button className="back" onClick={()=>step?setStep(step-1):go('today')}><ChevronLeft/> Back</button><div className="progressbar"><span style={{width:`${(step/questions.length)*100}%`}}/></div><small>QUESTION {step+1} OF {questions.length}</small><h1>{q.title}</h1><div className="scale">{Array.from({length:q.max},(_,i)=>i+1).map(n=><button key={n} onClick={()=>setAnswers({...answers,[q.id]:n})} className={answers[q.id]===n?'selected':''}>{n}</button>)}</div><div className="scale-label"><span>{q.low}</span><span>{q.high}</span></div>{error&&<p className="error">{error}</p>}<button className="primary bottom" onClick={next}>Continue</button></>}

function Learn(){return <><div className="page-title"><h1>Small resets</h1><Leaf/></div><p>Short activities for difficult moments. Choose only what feels useful.</p>{activities.map(([title,text],i)=><article className="activity" key={title}><div>{i+1}</div><section><small>{i===0?'2–3 MIN · RECOMMENDED':'2–5 MIN'}</small><h3>{title}</h3><p>{text}</p><details><summary>Start activity</summary><div className="activity-step">{text}<br/><br/>Stopping after this is completely okay.</div></details></section></article>)}</>}
function Progress({data}){const completed=data.tasks.filter(t=>t.done).length;const avg=data.checkins.length?Math.round(data.checkins.reduce((a,c)=>a+c.risk.score,0)/data.checkins.length):0;return <><div className="page-title"><h1>Progress, without pressure</h1><TrendingUp/></div><div className="stats"><article><small>CHECK-INS</small><b>{data.checkins.length}</b></article><article><small>TASKS COMPLETED</small><b>{completed}</b></article><article><small>AVG PRESSURE</small><b>{avg || '—'}</b></article></div><h2>Recent check-ins</h2>{data.checkins.slice(0,7).map((c,i)=><div className="trend" key={c.id||i}><span>{new Date(c.createdAt?.seconds?c.createdAt.seconds*1000:c.createdAt||Date.now()).toLocaleDateString()}</span><div><i style={{width:`${c.risk.score}%`}}/></div><b>{c.risk.score}</b></div>)}{!data.checkins.length&&<Empty title="Your trends will appear here" text="Complete a check-in whenever it feels helpful."/>}</>}
function Support({data}){const risk=data.checkins[0]?.risk;return <><div className="page-title"><h1>Support</h1><Heart/></div><article className="support-card"><h2>A summary you control</h2><p>{risk?`My current academic pressure is ${risk.band.toLowerCase()} (${risk.score}/100). A smaller first step and a clear priority would help.`:'Complete a check-in to prepare a short support summary.'}</p><button className="primary" disabled={!risk} onClick={()=>navigator.clipboard.writeText(`My current academic pressure is ${risk.band.toLowerCase()} (${risk.score}/100). A smaller first step and a clear priority would help.`)}>Copy summary</button></article><article className="notice"><CircleHelp/><div><b>Need urgent help?</b><p>Nuvora is not an emergency or healthcare service. Contact your university support service, NHS 111, or emergency services when appropriate.</p></div></article></>}
function SettingsPage({value,onChange}){return <><h1>Calm accessibility settings</h1><Setting label="Calm mode" text="Reduces visual density and uses softer contrast." checked={value.calmMode} onChange={v=>onChange({...value,calmMode:v})}/><Setting label="Reduced motion" text="Removes non-essential animation." checked={value.reducedMotion} onChange={v=>onChange({...value,reducedMotion:v})}/><h2>Text size</h2><div className="tabs">{[[1,'Standard'],[1.15,'Medium'],[1.3,'Large']].map(([v,l])=><button key={v} className={value.textScale===v?'active':''} onClick={()=>onChange({...value,textScale:v})}>{l}</button>)}</div></>}
function Setting({label,text,checked,onChange}){return <label className="setting"><div><b>{label}</b><p>{text}</p></div><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)}/></label>}
function Overwhelmed({data,uid,setData,go}){const [done,setDone]=useState(false);const task=data.tasks.find(t=>!t.done);return <div className="overwhelmed-page"><Leaf/><small>OVERWHELMED MODE</small>{done?<><h1>One step down.</h1><p>That is genuinely enough for right now.</p><button className="primary" onClick={()=>go('today')}>Back to Today</button></>:<><h1>Let’s make everything smaller.</h1><p>You do not need to solve the whole day.</p><article><small>YOUR ONE STEP</small><h2>{task?`Only open “${task.title}”.`:'Take one slow breath.'}</h2><p>You can stop immediately after that.</p></article><button className="primary" onClick={async()=>{setDone(true)}}>I did this step</button><button onClick={()=>go('today')}>Not now</button><span>No shame. You’ve got this.</span></>}</div>}
function MiniTask({task}){return <div className="mini"><span className={task.done?'checked':''}>{task.done&&<Check/>}</span><div><b>{task.title}</b><small>{task.step}</small></div></div>}
function Empty({title,text}){return <div className="empty"><Leaf/><h3>{title}</h3><p>{text}</p></div>}
